from run_noddi import visualize_result
import dill
import os
import argparse


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Takes a pickle file generated by the training of a model on the specific mri")
    parser.add_argument('--path', metavar='-p', type=str, help="The path to the location of the pickle file")
    parser.add_argument('--name', metavar='-n', type=str, help="The name of the image to be saved")

    args = parser.parse_args()

    try: 
        ## load the model 
        with open(args.path, "rb") as f:
            model = dill.load(f)

        ## visualize the model
        try:
            visualize_result(model, args.name)
        except:
            print("failed visualizing the model")
    except:
        print("failed loading the model")
